language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run lint
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  # local_dir: storybook-static
  on:
    branch: main
